### PR TITLE
removal of sfl, both from code and dependency definition

### PR DESCRIPTION
**Pull request by hugefatbastard**

### CODE REVIEW

**Comment by szpak** [comment]
slf4j is not massively used in jfairy (for now), but in general it is good to have an ability to log something. Why you would like to remove it completely?

**Comment by hugefatbastard** [comment]
Hi, run it without any configuration file provided. You will get this ugly red warning, no appenders configured..

**Comment by hugefatbastard** [comment]
hm, interesting stuff. Need to read how pull requests actually work. i wanted to pull just one commit...

**Comment by szpak** [comment]
PR usually compares two branches. You could have two different branches to separate those changes.

Regarding a message it is intentionally. As a user you can choose how to handle logging from jfairy. Just add logback or log4j bindings to your project. Take a loot at the page mentioned in the warning.

**Comment by jkubrynski** [comment]
We definitely should stay with slf4j - it's currently standard in java logging and if you provide any logging framework (which I assume is already in your application) no errors or warnings are shown.

**Comment by hugefatbastard** [comment]
yes guys, I got these arguments.
However I would like to argue a little bit. If you use logging statement directly in your lib, than you 'force' application that is using your lib to provide bridge/adapter. 

Imagine this lib become popular. What if 20% of apps is not going to use any logging system. (because of architectural decisions, could be many reason) . The first thing devs of this app will see is that warning, and why - because there is one logging statement of exception inside just one class.

And what if user decides to provide logger, then first rule he puts in the code is to ignore logging from NIP class, because he/she does not want to see (or care) that NIP is invalid. (true or false) from this method is sufficient.

In case of warnings from subcomponents, I would take different approach. Simply, propagate event from lib to app, and let application decide what to do with it.

But this is only suggestion. You are one to decide.

**Comment by mariuszs** [comment]
Maybe we should add [SimpleLogger](http://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html) as default dependency to silent all warnings?

**Comment by mariuszs** [comment]
Ok, default logger is NOP (no-operation) and this is good. If you want to do something more with logging read for example this post: http://saltnlight5.blogspot.com/2013/08/how-to-configure-slf4j-with-different.html

Most java libraries are using logging framework by default, this helps debugging and analysing.

**Comment by szpak** [comment]
> Maybe we should add SimpleLogger as default dependency to silent all warnings?

That would provide a conflict and force users to exclude transitive dependency to SimpleLogger.

@hugefatbastard If you didn't like to see any logging from jfairy you could just disable logging from `io.codearte.jfairy` - for example see the [configuration](http://logback.qos.ch/manual/configuration.html) in Logback.

**Comment by hugefatbastard** [comment]
@szpak this is what I will do
@mariuszs Really? Mockito, junit, guava, apache commons. I do not think any of these popular java libraries using sfl4j or log4j

**Comment by szpak** [comment]
@hugefatbastard 9000+ project in Maven Central uses slf4j-api - you can [browse them](http://mvnrepository.com/artifact/org.slf4j/slf4j-api/usages).

**Pull request closed without merging**
