### PR TITLE
Create jfairy_it.yml

### PR DESCRIPTION
**Pull request by djechelon**
Italian language resources

### CODE REVIEW

**Comment by mariuszs** [comment]
+1 awesome

**Comment by OlgaMaciaszek** [comment]
Thank you for this PR @djechelon 
This will allow the IT names to be incorporated in the data generation, however for the numbers and other data to be generated according to the IT rules, a separate FairyModule and dedicated producers will have to be added.

I'm merging this now, and then I will make a commit adding IT to language code so that it can be used.

**Comment by djechelon** [comment]
To be more precise, phone numbers et similar may have to start with a valid prefix like regional landline (02, 06, 011, 081) or cell phone carrier (333, 334, 347, 348, 392...).

For example +39 0252145845 is syntactically valid, +39 3495280894 also but +39 585315631 has no meaning. But that is a more advanced matter, I think

**Comment by OlgaMaciaszek** [comment]
Yes. Also, generally the ID,  Social Security and passport numbers are generated differently for each country. To achieve   that we have separate FairyModules for , EN, PL and ES as well as separate data producers   for different kinds of numbers.

**Comment by djechelon** [comment]
Aha, I didn't know about it so far

**Pull request merged**
