### PR TITLE
Add locale Address format support 

### PR DESCRIPTION
**Pull request by andidev**
...in Address toString method and add two new methods getAddressLine1() + getAddressLine2() that gives the address formated according to the locale.

**English**
```
println address.toString()
11 Ford Street APT 313
San Francisco 28664

println address.addressLine1()
52 Stillwell Avenue

println address.addressLine1()
Washington 23519
```

**Polish**
```
println address.toString()
Szulborska 11
91-528 Cedzyna

println address.addressLine1()
Patriotów 37

println address.addressLine1()
51-977 Srem
```

**Swedish**
```
println address.toString()
Götgatan 73
528 66 Kristianstad

println address.addressLine1()
Norra Agnegatan 120

println address.addressLine1()
235 19 Örnsköldsvik
```

**Spanish**
```
println address.toString()
Vieja, 39 327
33.915 Cáceres

println address.addressLine1()
Doctor Esquerdo, 96 278

println address.addressLine1()
86.125 Orense
```

### CODE REVIEW

**Comment by andidev** [comment]
Closing issue #11

**Comment by OlgaMaciaszek** [comment]
@andidev Thanks for this PR. Looks good :)
Please fix the test method names - some tests for Address Providers other than SV contain "SV" in their method names instead of the appropriate country tags.

**Comment by andidev** [comment]
@OlgaMaciaszek 
Remarks should be fixed now

**Comment by OlgaMaciaszek** [comment]
Looks good @andidev :).
Merging.

**Pull request merged**
