### PR TITLE
Add new language support Swedish (SV)

### PR DESCRIPTION
**Pull request by andidev**
YML Datafile
- [x] jfairy_sv.yml

Person
- [x] `fairy.person().nationalIdentificationNumber()` -> `PersonalIdentityNumberProvider`
- [x] `fairy.person().nationalIdentityCardNumber()` -> `SvNationalIdentityCardNumberProvider`
- [x] `fairy.person().passportNumber()` -> `SvPassportNumberProvider`

Company
- [x] `fairy.company().vatIdentificationNumber()` -> `MomsnrProvider`

### CODE REVIEW

**Comment by andidev** [comment]
Tested and it seems to work! 

Though it look like I need to implement something to get the nationalIdentificationNumber to be correct.

**Comment by andidev** [comment]
I'm not sure how to implement the swedish version of NationalIdentityCardNumberProvider.
I need to pass some properties to it (DateTime dateOfBirth and Person.Sex sex). Any ideas on that?

**Comment by mariuszs** [comment]
@OlgaMaciaszek can you look into it?

**Comment by OlgaMaciaszek** [comment]
Sure. Will review it today.

**Comment by OlgaMaciaszek** [comment]
Hello @andidev, thank you for your contribution :). 
The main issue here seems to be that in Poland -which was the base model- we have 2 kinds of numbers: 
1. Identity Card Number (the number on your ID card, which is being changed every few years), created using classes that implement NationalIdentityCardNumberProvider; 
2. Personal Identity Number that everybody gets for life and is created by classes that implement Provider<NationalIdentificationNumber>;
I guess it should be similar in SV? In this case, the PersonalIdentityNumberProvider should rather implement Provider<NationalIdentificationNumber> and not NationalIdentityCardNumberProvider and the ID card number generation should be done by a different class.

Some other suggested improvements:
- The JFairy lib pays attention to the actual ways in which the numbers are generated for a given country and I can see this reflected in your PersonalIdentificationNumber class, however the SvPassportNumberProvider class just returns 8 random digits. Is it really the way they are generated in SV? If not, please read up on the rules of passport number generation in SV and adjust your implementation
- isValid() method in PersonalIdentityNumberProvider is a duplicate of the method with the same name in another class; Please rather extract it somewhere than duplicate the same code
- the coverage has decreased - please see which parts of your new additions are not covered by tests in order to improve it. We strive to maintain a 90% test coverage

Issue with the dateOfBirth() and sex() methods:
I see that the PeselProvider (from PL module) is actually hard-coded in the PersonProvider, so the methods you have added in PersonalIdentityNumberProperties will not be called. This is actually a bug in the lib. It should use an injected instance of Provider<NationaldentificationNumber> injected through constractor and resolved appropriately for each country. You can fix it if you like. If not, please let me know and I will fix it shortly.

**Comment by andidev** [comment]
Yes I think you may be right about 1 and 2. Now it makes more sense.

I am not sure how the PersonalIdentificationNumber is generated actually. I'll dig into it a little deeper. I have not found any info about it yet though I have not searched that mutch.

The PR needs some more work and I'll look into the code covarage and isValid problem later tonigth. I need to fix the SvVATIdentificationNumberProviderSpec as well so this PR is far away from finnished.

I'll return to you for a second code review. Thanks for the thought on the current one!

**Comment by szpak** [comment]
@andidev Regarding Personal identification number in Sweden maybe [this](https://en.wikipedia.org/wiki/Personal_identity_number_%28Sweden%29#Checksum) will be helpful

**Comment by andidev** [comment]
Thanks, this is actually what I already implemented but with the NationalIdentityCardNumberProvider. I'm gonna do the necessary refactoring as soon as I get home. The problem part is actually how to implement the real NationalIdentityCardNumberProvider. Looks like there is such a number in national id cards e.g. https://upload.wikimedia.org/wikipedia/en/9/93/SwedishIDcard2012.png
I'm new to this number though. Maybe it is a general European Union number. 

The VAT number is no problem either since it is similar to the personal identification number (same validation logic but it may contain random numbers instead of the birth of date depending on the company type. Though I still need to implement this. 

The passport number makes me clueless though. I need to investigate if there is some logic to implement here as well or if it is just random numbers.

**Comment by OlgaMaciaszek** [comment]
Great. Waiting for more changes.

**Comment by andidev** [comment]
So I'm having trouble replacing the PeselFactory with the new PersonalIdentityNumberFactory that should be used for the swedish locale when calling `fairy.person().nationalIdentificationNumber()`.

Any ideas on how to do that with Guice? I tried to create a general Factory interface called NationalIdentificationNumberFactory that creates a general NationalIdentificationNumberProvider with NationalIdentificationNumberProperties. And then let both PeselFactory and PersonalIdentityNumberFactory extend the general factory and override the pruduce method return type to PeselProvider or PersonalIdentityNumberProvider. Then I make sure that only one factory is installed in the country specific FairyModules.Though I can't seem to get the guice dependency injection to work.

I did these changes in a separate branch:
https://github.com/Codearte/jfairy/compare/master...andidev:add-swedish-locale-support-general-NationalIdentificationNumberFactory-attempt?expand=1

**Comment by andidev** [comment]
Or maybe the solution is to create another field in the Person object, e.g. fairy.person().personalIdentityNumber()? But I guess this is not wanted.

**Comment by OlgaMaciaszek** [comment]
I guess the easiest way would be create an interface NationalIdentificationNumberProvider, make any classes imlementing Provider<NationalIdentificationNumber> implement that instead and add a binding to that implementation in the country FairyModule classes. Then you could use that interface instead of the PeselFactory in the PersonProvider to automatically resolve the right country class. Have you tried such an approach?

**Comment by andidev** [comment]
That is what I have tried in this [branch](https://github.com/Codearte/jfairy/compare/master...andidev:add-swedish-locale-support-general-NationalIdentificationNumberFactory-attempt?expand=1) but since the provider takes the date of birth and gender as constructor arguments I need to define factory interfaces as well. And this is where guice fail to create and inject the correct factory when trying to use a general NationalIdentificationNumberFactory in the PersonProvider while installing PeselNumberFactory and PersonalIdentityNumberFactory (that extends the  NationalIdentificationNumberFactory) in country FairyModule classes. I'm new to guice so maybe it's not possible to do this way. It feels like it's to complex use case for the builder. I don't remember the exact error guice tells me but I think it may be the guice builder factory failing to create the factory implementation classes. Maybe it works creating them manually.

**Comment by OlgaMaciaszek** [comment]
I'm not really very experienced with Guice either - have only used it here, but I look at it during the weekend and try to find some solution.

**Comment by andidev** [comment]
So I managed to create the factories manually and bind them so I'll soon update this PR

**Comment by andidev** [comment]
@OlgaMaciaszek 
Is it okay to add http://commons.apache.org/proper/commons-math/ as a dependency?
I would like to use [EnumeratedDistribution](http://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math3/distribution/EnumeratedDistribution.html) for getting random company types according to statistics for swedish VATIdentificationNumbers.

**Comment by andidev** [comment]
So it should be done. Some improvements could be made with the commons-math lib as mentioned but it is not necessary.

One big change is that `fairy.person().nationalIdentificationNumber()` will only return a value for locale `PL` and `SV`. For all other locales it will return an empty string. Earlier it has always returned the polish Pesel number for all locales but that felt wrong. Please let me know if this is not ok and I'll revert it.  

The Swedish Passport Number and National Identity Card Number are only random number implementations. I was not able to find any information on how these numbers are generated so this is currently best implementation. Though the number is always an 8 digit number. That I am sure of. This could also be improved later on by anybody with more knowledge if needed. Another option is reverting commit b45152b so that empty strings are returned instead. 

@OlgaMaciaszek 
Could you please review and merge if you are satisfied?

**Comment by OlgaMaciaszek** [comment]
Thanks @andidev. This looks good :). I think one thing that still should be changed is the Swedish variable and enum names. I know they refer to some Swedish document characteristics, however, this is quite unreadable for anybody that doesn't understand Swedish. I think the English translations of the concepts should be used instead.

**Comment by andidev** [comment]
I'll try to translate them then. I actually tried to do that earlier though it was not an easy task and I gave it up. I'll keep the swedish translations as comments.

**Comment by andidev** [comment]
@OlgaMaciaszek 
Done!

**Comment by OlgaMaciaszek** [comment]
Thank you @andidev . Could you also change `MomsnrProvider`
`MOMSNRNR_LENGTH`
`ENSKILD_FIRMA_UPPER_AGE_LIMIT = 16;`
`ENSKILD_FIRMA_LOWER_AGE_LIMIT = 100`

etc.? It's difficult to understand what `ENSKILD_FIRMA` is and I think the class should rather be named `SvVATIdentificationNumberProvider`.

Btw., I also realise, we have the `PeselProvider` for the PL version, but I suppose this should also be changed, so I will fix it just after merging your PR.

**Comment by andidev** [comment]
Good point! Makes more sense. Only reason I called it Momsnr was since the other providers seemed to be to be translated. 
I'll fix the Pesel classes as well. There are some other providers as well that are translated. Should I translate and rename them as well?

**Comment by OlgaMaciaszek** [comment]
I think it's a good idea.

**Pull request merged**
