### PR TITLE
made Person and Address API self-consistent

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Please feel free to suggest any changes/enhancements.

Thanks for providing jfairy. :)

### CODE REVIEW

**Comment by jkubrynski** [comment]
Hi! We had long discussion about get prefix and we're aware there are inconsistencies here. The argument for using get* is that it allows you to write just address.street in Groovy, which is often used in tests.

**Comment by PascalSchumacher** [comment]
Hi,

from groovy you can use address.street anyway as groovy allows access to private members. (I already use things like address.streetNumber in my Groovy code ;).)

But from Java using address.postalCode() is more convenient than using address.getPostalCode(). Furthermore it's confusing when most of API uses getters without the "get" prefix and a few methods require the prefix.

Of course it's your project, so you decide. :) Feel free to reject my pull request.

**Comment by mariuszs** [comment]
maybe we can both type of methods without deprecation?

**Comment by PascalSchumacher** [comment]
I am fine with having both type of methods. I can updated the pull request if everyone is fine with this solution. No  need to hurry, I can wait if you require further time to discuss/decided.

**Comment by mariuszs** [comment]
There are some problems with access to private fields from groovy, IDE warns about this kind of access and this is not working with compile static.

In my opion we have two options:

* make private fields public
* add getFoo() and foo()



About groovy and private...
> it looks like this was a bug in groovy from the beginning, but nobody bothered to fix it because for such a dynamically and reflectively capable language private is just a documentation anyways.
http://www.gmarwaha.com/blog/2009/02/02/groovy-private-is-not-private/

**Comment by PascalSchumacher** [comment]
I do not know jfairy good enough, but if everything field is final anyway making them public would not hurt and make access from java read even nicer. Eclipse does not emit any warning for this, but maybe other IDEs do.

**Comment by PascalSchumacher** [comment]
Hi @jkubrynski @mariuszs

any updates?

I updated the pull request and removed the deprecation from the getX methods.

**Comment by mariuszs** [comment]
:+1:

**Comment by mariuszs** [comment]
@szpak What do you think? Maybe we should use public fields instead?

**Comment by jkubrynski** [comment]
@PascalSchumacher sorry for delay from our side, but it's pretty general change and it's hard to make a decision. I personally think we should choose single convention and stick to it. In Java world `name()` is something which looks better, but in Groovy (which is major usecase in tests) developers usually prefer just `name`. IMHO that drives us to `get*` convention. So I vote for getters

**Comment by OlgaMaciaszek** [comment]
+1 for getters

**Comment by andidev** [comment]
+1 for consistency

**Comment by andidev** [comment]
I would say that in java get... does look better if the object is a pojo. Which is actually the case for the Person and Address objects.

**Comment by OlgaMaciaszek** [comment]
Ok, I think it makes sense. Could you improve the coverage? I will merge it then.

**Comment by andidev** [comment]
I'll could do a separate PR where I refactor all pojos to use getters. This PR does actually the opposite and removes the current getters in the address object.

**Comment by PascalSchumacher** [comment]
@andidev No sure what you mean, the pull request does not remove anything it just adds.

**Comment by andidev** [comment]
Oh yes you are right Pascal. @OlgaMaciaszek So is both getters and and non getter methods wanted for all pojos or is it only getters or only non getters? Not sure what you ment.
I ment only getters in my comment since that is the java style of doing it and since this is a java library.

**Comment by OlgaMaciaszek** [comment]
Sorry, I had to delete the comment above - I've written it under the wrong PR.
When it comes to this one, I agree with @jkubrynski

**Pull request closed without merging**
